### PR TITLE
Fix Blender 4.2 compatibility #28

### PR DESCRIPTION
**Pull request by ra100**
This should fix the issue where this addon didn't do anything on Blender 4.2.
I've tried it on 2.93.0 and looked working fine, so I hope, I didn't break anything.

### CODE REVIEW

**Comment by cessen** [comment]
There are a lot of changes in here that don't seem relevant to making this work on Blender 4.2, which makes it tricky to review.  It's not clear what the change is that fixes it.  I don't mean to make more work for you, but could you submit another PR with just the changes to make it work on 4.2?

**Comment by ra100** [comment]
Sure, sorry, I'll remove unrelated changes, I'll try to make it as small as possible.

**Comment by ra100** [comment]
I am sorry, is it possible that it was fixed on Blender 4.2 side? I've just tried to remove and install original zip, and it's working. Without any code change.

**Comment by ra100** [comment]
In the end, this doesn't seem to fix anything. I'll just take some small parts, harmless changes and create a PR, so not all work is lost :)

**Comment by cessen** [comment]
Ah, interesting.  It's possible it was fixed on the Blender side, yeah.  I'll look into it and double-check when I get the chance, just to be sure.

**Pull request closed without merging**
